FROM node:lts

RUN apt update && apt install -y --no-install-recommends git zsh

WORKDIR /app
COPY . /app
RUN npm install

RUN chsh -s /usr/bin/zsh root
RUN git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh && cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
